openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Arch Lab Example API'
  description: Пример API для первого домашнего задания по курсу Архитектура программных систем
servers:
  - url: http://localhost:8080
    description: Example server
paths:
  /auth:
    get:
      summary: Проверка аутентификации
      responses:
        '200':
          description: User ID
          content:
            application/json:
              schema:
               type: string
        401:
          description: Not authentication
          content:
            application/json:
              schema:
                type: string
  /user:
    get:
      summary: Поиск пользователей по имени, фамилии и/или логину
      parameters:
      - name: name
        description: Имя
        in: query
        required: false
        schema:
          type: string
      - name: surname
        description: Фамилия
        in: query
        required: false
        schema:
          type: string
      - name: login
        description: Логин
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: The users for the provided masks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users'
        404:
          description: No user found for the provided mask
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Добавление нового пользователя
      parameters:
      - name: name
        description: Имя пользователя
        in: query
        required: true
        schema:
          type: string
      - name: surname
        description: Фамилия пользователя
        in: query
        required: true
        schema:
          type: string
      - name: email
        description: email пользователя
        in: query
        required: true
        schema:
          type: string
      - name: title
        description: Форма обращение к пользователя 
        in: query
        required: true
        schema:
          type: string
      - name: login
        description: login пользователя
        in: query
        required: true
        schema:
          type: string
      - name: password
        description: пароль пользователя
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Идентификатор, добавленного пользователя
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Ошибка добавления пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    user_id:
      description: Уникальный идентификатор пользователя
      type: integer
    users:
      type: array
      items:
        $ref: '#/components/schemas/user'
    user:
      type: object
      required:
        - id
        - name
        - surname
        - email
        - title
        - login
        - password
      properties:
        id:
          $ref: '#/components/schemas/user_id'
        name:
          type: string
        surname:
          type: string
        email:
          type: string
        title:
          type: string
        login:
          type: string
        password:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: Сообщение о ошибке
          type: string
  securitySchemes:
      basicAuth:     
        type: http
        scheme: basic
security:
  - basicAuth: []